### ISSUE TITLE
Not compatable with Python3: TypeError: 'dict_keys' object does not support indexing

### ISSUE THREAD

**Issue by tonyho** [veo-labs/python-engineio-client#1]
This module works fine with Python2, but not working with Python3(Python3.4, and 3.5 both tried): 
```
Traceback (most recent call last):
  File "c2.py", line 64, in <module>
    chat.connect()
  File "/usr/local/lib/python3.4/dist-packages/python_socketio_client-0.1-py3.4.egg/socketio_client/socket.py", line 47, in connect
    self.manager.connect()   # Ensure connected
  File "/usr/local/lib/python3.4/dist-packages/python_socketio_client-0.1-py3.4.egg/socketio_client/manager.py", line 65, in connect
    self.engine.open()
  File "/usr/local/lib/python3.4/dist-packages/python_engineio_client-1.1-py3.4.egg/engineio_client/client.py", line 39, in open
    transport_name = self.transports[0]
TypeError: 'dict_keys' object does not support indexing
```

How can we fix this?

**Comment by gcharles82** [comment]
Yes, python-engineio-client was not developed to be Python3 compliant. I'm not surprised.
Python 3 support will probably be added this year, but I don't know when.
